<?php

use Xian\Handlers\{
    Bag,
    Chongwu,
    Club,
    CreateRole,
    Daoju,
    Fangshi,
    Guaiwu,
    Index,
    Manual,
    Map,
    NowMid,
    Npc,
    Ornament,
    Peifang,
    PVE,
    PVP,
    Rank,
    Role,
    Setting,
    Task,
    Xiulian,
    Yaopin,
    Zhuangbei,
    Im,
    Relationship,
    VIP,
    Party,
    Activity,
};
use Xian\Handlers\Admin\{
    MapEditor,
    NPC as AdminNPC,
    Monster as AdminMonster,
    Ornament as AdminOrnament,
    Operation as AdminOperation,
    Condition as AdminCondition,
    Area as AdminArea,
};

return [
    'index' => [Index::class, 'showLogin'],
    'do-login' => [Index::class, 'doLogin'],
    'logout' => [Index::class, 'logout', false],
    'register' => [Index::class, 'showRegister'],
    'do-register' => [Index::class, 'doRegister', false],
    'locked' => [Index::class, 'showLocked'],
    'cj' => [CreateRole::class, 'displayCreateView'],
    'cjplayer' => [CreateRole::class, 'create', false],
    'gomid' => [NowMid::class, 'displayNowMid'],
    'move-to-mid' => [NowMid::class, 'moveToMid', false],
    'pfinfo' => [Peifang::class, 'peifangInfo'],
    'npc' => [Npc::class, 'handle'],
    'show-heal' => [Npc::class, 'showHeal'],
    'do-heal' => [Npc::class, 'doHeal'],
    'show-shop' => [Npc::class, 'showShop'],
    'show-shop-item-info' => [Npc::class, 'showShopItemInfo'],
    'do-shop' => [Npc::class, 'doShop', false],
    'show-menpai' => [Npc::class, 'showMenpai'],
    'do-menpai' => [Npc::class, 'doMenpai'],
    'show-peifang' => [Npc::class, 'showPeifang'],
    'do-peifang' => [Npc::class, 'doPeifang', false],
    'show-conversation' => [Npc::class, 'showConversation'],
    'do-conversation' => [Npc::class, 'doConversation'],
    'pve' => [PVE::class, 'showPve'],
    'begin-pve' => [PVE::class, 'beginPve'],
    'do-pve' => [PVE::class, 'doPve', false],
    'do-member-pve' => [PVE::class, 'doMemberPve', false],
    'pve-log' => [PVE::class, 'showPveLog'],
    'delete-pve-log' => [PVE::class, 'deletePveLog'],
    'getbagdj' => [Bag::class, 'showDaoju'],
    'sell-daoju' => [Bag::class, 'sellDaoju', false],
    'getginfo' => [Guaiwu::class, 'gInfo'],
    'djinfo' => [Daoju::class, 'djInfo'],
    'sell-djinfo' => [Daoju::class, 'sellDjInfo', false],
    'use-djinfo' => [Daoju::class, 'useDjInfo'],
    'task' => [Task::class, 'showTask'],
    'accept-task' => [Task::class, 'acceptTask'],
    'complete-task' => [Task::class, 'completeTask', false],
    'mytask' => [Task::class, 'showMyTasks'],
    'mytaskinfo' => [Task::class, 'myTask'],
    'allmap' => [Map::class, 'showAll'],
    'show-area' => [Map::class, 'showArea'],
    'zhuangtai' => [Role::class, 'showStatus'],
    'show-equips' => [Role::class, 'showEquips'],
    'player-skills' => [Role::class, 'showSkills'],
    'player-skill-info' => [Role::class, 'showSkillInfo'],
    'select-equip' => [Role::class, 'selectEquip'],
    'xxzb' => [Role::class, 'takeOff'],
    'setzbwz' => [Role::class, 'wear'],
    'getplayerinfo' => [Role::class, 'showOtherStatus'],
    'relationship' => [Relationship::class, 'showRelationship'],
    'add-relationship' => [Relationship::class, 'addRelationship'],
    'delete-relationship' => [Relationship::class, 'deleteRelationship'],
    'liaotian' => [Im::class, 'showMessages'],
    'show-my-item' => [Bag::class, 'showMyItem'],
    'getbagzb' => [Bag::class, 'showZhuangbei'],
    'sell-getbagzb' => [Bag::class, 'sellZhuangbei', false],
    'delete-getbagzb' => [Bag::class, 'deleteZhuangbei', false],
    'getbagpf' => [Bag::class, 'showPeifang'],
    'getbagyp' => [Bag::class, 'showYaopin'],
    'getbagjn' => [Bag::class, 'showFuzhuan'],
    'ranks' => [Rank::class, 'showRanks'],
    'paihang' => [Rank::class, 'showLevelRank'],
    'fortune-rank' => [Rank::class, 'showFortuneRank'],
    'goxiulian' => [Xiulian::class, 'showXiulian'],
    'endxiulian' => [Xiulian::class, 'endXiulian'],
    'startxiulian' => [Xiulian::class, 'startXiulian'],
    'fangshi-daoju' => [Fangshi::class, 'showDaoju'],
    'fangshi-item-info' => [Fangshi::class, 'showItemInfo'],
    'fangshi-buy-daoju' => [Fangshi::class, 'buyDaoju'],
    'fangshi-zhuangbei' => [Fangshi::class, 'showZhuangbei'],
    'fangshi-buy-zhuangbei' => [Fangshi::class, 'buyZhuangbei'],
    'zbinfo' => [Zhuangbei::class, 'zbInfo'],
    'chakanzb' => [Zhuangbei::class, 'zbInfo', false],
    'sell-zbinfo' => [Zhuangbei::class, 'sellZbInfo'],
    'upzb' => [Zhuangbei::class, 'upZbInfo'],
    'zbinfo_sys' => [Zhuangbei::class, 'showSysInfo'],
    'shengxing-list' => [Zhuangbei::class, 'shengxingList'],
    'show-shengxing-material' => [Zhuangbei::class, 'showShengxingMaterial'],
    'shengxing' => [Zhuangbei::class, 'shengxing'],
    'qianghua-list' => [Zhuangbei::class, 'qianghuaList'],
    'show-qianghua-material' => [Zhuangbei::class, 'showQianghuaMaterial'],
    'qianghua' => [Zhuangbei::class, 'qianghua'],
    'clublist' => [Club::class, 'showList'],
    'club' => [Club::class, 'showClub'],
    'out-club' => [Club::class, 'out'],
    'join-club' => [Club::class, 'join'],
    'delete-club' => [Club::class, 'delete'],
    'zhiwei-club' => [Club::class, 'setZhiwei'],
    'ypinfo' => [Yaopin::class, 'info'],
    'setyp' => [Yaopin::class, 'setYaopin'],
    'useyp' => [Yaopin::class, 'useYaopin'],
    'tupo' => [Role::class, 'showTupo'],
    'do-tupo' => [Role::class, 'doTupo'],
    'chongwu' => [Chongwu::class, 'showChongwu'],
    'cz-chongwu' => [Chongwu::class, 'chuzhan'],
    'cq-chongwu' => [Chongwu::class, 'chouqu'],
    'fs-chongwu' => [Chongwu::class, 'fangsheng'],
    'sh-chongwu' => [Chongwu::class, 'shouhui'],
    'show-ronghe' => [Chongwu::class, 'showRonghe'],
    'do-ronghe' => [Chongwu::class, 'doRonghe'],
    'fh-chongwu' => [Chongwu::class, 'doFuhua'],
    'cwinfo' => [Chongwu::class, 'cwInfo'],
    'pvp' => [PVP::class, 'showPvp'],
    'do-pvp' => [PVP::class, 'doPvp'],
    'pvp-defense' => [PVP::class, 'showDefense'],
    'do-defense' => [PVP::class, 'doDefense'],
    'pvp-log' => [PVP::class, 'showPvpLog'],
    'show-shortcuts' => [Setting::class, 'showShortcuts'],
    'select-shortcut-skill' => [Setting::class, 'selectShortcutSkill'],
    'select-shortcut-item' => [Setting::class, 'selectShortcutItem'],
    'set-shortcut' => [Setting::class, 'setShortcut'],
    'show-combat-condition' => [Setting::class, 'showCombatCondition'],
    'show-add-combat-condition' => [Setting::class, 'showAddCombatCondition'],
    'add-combat-condition' => [Setting::class, 'addCombatCondition', false],
    'delete-combat-condition' => [Setting::class, 'deleteCombatCondition', false],
    'up-combat-condition' => [Setting::class, 'upCombatCondition', false],
    'select-combat-skill' => [PVE::class, 'selectCombatSkill'],
    'select-combat-item' => [PVE::class, 'selectCombatItem'],
    'runaway' => [PVE::class, 'runaway'],
    'show-ornament' => [Ornament::class, 'showOrnament'],
    'operate' => [Ornament::class, 'operate'],
    'ornament-mining' => [Ornament::class, 'mining'],
    'learn-manual' => [Manual::class, 'learnManual', false],
    'learn-skill' => [Manual::class, 'learnSkill', false],
    'use-skill-outside' => [Manual::class, 'useSkillOutside'],
    'summon-pet' => [Manual::class, 'summonPet'],
    'show-loc' => [MapEditor::class, 'showMid'],
    'show-create-loc' => [MapEditor::class, 'showCreateMid'],
    'create-loc' => [MapEditor::class, 'createMid'],
    'admin-show-update-loc' => [MapEditor::class, 'showUpdateLoc'],
    'admin-update-loc' => [MapEditor::class, 'updateLoc'],
    'admin-loc-disconnect' => [MapEditor::class, 'disconnect'],
    'admin-loc-connect' => [MapEditor::class, 'connect'],
    'admin-loc-show-connections' => [MapEditor::class, 'showConnections'],
    'admin-npc-list' => [AdminNPC::class, 'npcList'],
    'admin-set-npc' => [AdminNPC::class, 'setLocation'],
    'admin-unset-npc' => [AdminNPC::class, 'unsetLocation'],
    'admin-delete-npc' => [AdminNPC::class, 'delete'],
    'admin-show-create-npc' => [AdminNPC::class, 'showCreate'],
    'admin-create-npc' => [AdminNPC::class, 'doCreate'],
    'admin-monster-list' => [AdminMonster::class, 'monsterList'],
    'admin-set-monster' => [AdminMonster::class, 'setLocation'],
    'admin-unset-monster' => [AdminMonster::class, 'unsetLocation'],
    'admin-delete-monster' => [AdminMonster::class, 'delete'],
    'admin-show-create-monster' => [AdminMonster::class, 'showCreate'],
    'admin-create-monster' => [AdminMonster::class, 'doCreate'],
    'admin-ornament-list' => [AdminOrnament::class, 'ornamentList'],
    'admin-set-ornament' => [AdminOrnament::class, 'setLocation'],
    'admin-unset-ornament' => [AdminOrnament::class, 'unsetLocation'],
    'admin-show-ornament' => [AdminOrnament::class, 'showOrnament'],
    'admin-show-edit-ornament' => [AdminOrnament::class, 'showEdit'],
    'admin-create-ornament' => [AdminOrnament::class, 'save'],
    'admin-delete-ornament' => [AdminOrnament::class, 'deleteOrnament'],
    'admin-ornament-unset-condition' => [AdminOrnament::class, 'unsetCondition'],
    'admin-operation-list' => [AdminOperation::class, 'operationList'],
    'admin-set-operation' => [AdminOperation::class, 'setOperation'],
    'admin-unset-operation' => [AdminOperation::class, 'unsetOperation'],
    'admin-operation-redirect' => [AdminOperation::class, 'redirectToSource'],
    'admin-show-create-operation' => [AdminOperation::class, 'showCreate'],
    'admin-create-operation' => [AdminOperation::class, 'save'],
    'admin-condition-list' => [AdminCondition::class, 'conditionList'],
    'admin-show-create-condition' => [AdminCondition::class, 'showCreate'],
    'admin-create-condition' => [AdminCondition::class, 'save'],
    'admin-area-list' => [AdminArea::class, 'areaList'],
    'admin-show-create-area' => [AdminArea::class, 'showCreate'],
    'admin-create-area' => [AdminArea::class, 'save'],
    'admin-delete-area' => [AdminArea::class, 'delete'],
    'test' => [Index::class, 'test'],
    'about' => [Index::class, 'showAbout'],
    'tutorial' => [Index::class, 'showTutorial'],
    'maintenance' => [Index::class, 'showMaintenance'],
    'vip' => [VIP::class, 'showAdvantage'],
    'party-member' => [Party::class, 'showPartyMembers'],
    'party' => [Party::class, 'showParties'],
    'party-creation-form' => [Party::class, 'showCreationForm'],
    'create-party' => [Party::class, 'createParty'],
    'join-party' => [Party::class, 'joinParty'],
    'allow-party-member' => [Party::class, 'allowPartyMember'],
    'reject-party-member' => [Party::class, 'rejectPartyMember'],
    'remove-party-member' => [Party::class, 'removePartyMember'],
    'leave-party' => [Party::class, 'leaveParty'],
    'follow-leader' => [Party::class, 'followLeader'],
    'unfollow-leader' => [Party::class, 'unfollowLeader'],
    'delete-party' => [Party::class, 'deleteParty'],
    'toggle-party-request' => [Party::class, 'togglePartyRequest'],
    'activity-list' => [Activity::class, 'showList'],
    'activity-qiandao' => [Activity::class, 'showQiandao'],
    'activity-do-qiandao' => [Activity::class, 'doQiandao', false],
    'activity-redeem-code' => [Activity::class, 'showRedeemCode'],
    'activity-do-redeem-code' => [Activity::class, 'doRedeemCode'],
];
